### ISSUE TITLE
[IIDM v1.2] Migrations of extensions to new API

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-iidm4cpp#120]
* **Do you want to request a *feature* or report a *bug*?**
Neither - Migration following an API change

* **What is the current behavior?**
`MergedXNode`, `CoordinatedReactiveControl`, `TwoWindingsTransformerPhaseAngleClock`, `ThreeWindingsTransformerPhaseAngleClock`, `CgmesModelExtension`, `CgmesConversionContextExtension` and `EntsoeArea` are still implemented using the deprecated extension API.

* **What is the expected behavior?**
These extensions should be implemented using the new extension API.

* **What is the motivation / use case for changing the behavior?**
Being able to create custom implementations of these extensions.

* **Please tell us about your environment:**
  - PowSyBl Version: 1.0.1

**Other information**
The corresponding PR in java are:
powsybl/powsybl-core#1255
powsybl/powsybl-core#1272
powsybl/powsybl-core#1336
powsybl/powsybl-core#1339
powsybl/powsybl-core#1341
powsybl/powsybl-core#1342
powsybl/powsybl-core#1343

**Comment by sebalaig** [comment]
Fixed in PRs #150, #151, #152, #153 and #154
