### ISSUE TITLE
[IIDM v1.2] Fix how to merge two dangling lines in a tie line.

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-iidm4cpp#123]
* **Do you want to request a *feature* or report a *bug*?**
Bug
https://github.com/powsybl/powsybl-core/pull/1216

In this PR, we ensure that TieLine implementation in Java and C++ are equivalent, specially in the computation of susceptance and conductance.

**Comment by sebalaig** [comment]
Nothing to do because the associated feature does not exist in C++.
