### ISSUE TITLE
[IIDM v1.2] Remove the upper bound for Hvdc converter station lossFactor

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-iidm4cpp#128]
* **Do you want to request a *feature* or report a *bug*?**
Bug fix
https://github.com/powsybl/powsybl-core/pull/1273
https://github.com/powsybl/powsybl-core/pull/1275
https://github.com/powsybl/powsybl-core/pull/1280

In this PR, we remove the integrity check for the upper bound of the converter station's lossFactor. We also change the convention of the lossFactor that is a percentage.

**Comment by sebalaig** [comment]
Fixed in PR #149
