### ISSUE TITLE
[IIDM 1.3] A dangling line should be considered as branch and not more as feeder

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-iidm4cpp#134]
* **Do you want to request a *feature* or report a *bug*?**
Bug fix

* **What is the current behavior?*
A dangling line  is considered as a feeder, even after merging, which is problematic in retrieving correct buses.

* **What is the expected behavior?**
A merged dangling line should be considered as a branch.

**Other information**
cf powsybl/powsybl-core#1340

**Comment by mathbagu** [comment]
Fixed in #175
