### ISSUE TITLE
[IIDM 1.2] Identifiable.name is optional + introduce getOptionalName(), getNameOrId() + deprecate getName()

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-iidm4cpp#135]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
`Identifiable.getName()` never returns `null`: either it returned the defined name or the id.

* **What is the expected behavior?**
`name` attribute should not be systematic: the API should be clearer about returning the real name or the `id`. New methods `getOptionalName()` and `getNameOrId()` are hence introduced.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

cf. powsybl/powsybl-core#1243

**Comment by sebalaig** [comment]
Duplication of issue #124, fixed by PR #142. => closed
