### ISSUE TITLE
[IIDM 1.3] Add hasTemporaryLimits() method to CurrentLimitsAdder

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-iidm4cpp#156]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
There is no way to know if temporary limits have been added in a `CurrentLimitsAdder` object

* **What is the expected behavior?**
We should know if a temporary limit has been added in a `CurrentLimitsAdder` object

* **What is the motivation / use case for changing the behavior?**
In some conversion (CGMES), it indicates if the adder is valid or not and can be added or not.

* **Please tell us about your environment:**
  - PowSyBl Version: 3.5.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)
cf. powsybl/powsybl-core#1372

(if a question doesn't apply, you can delete it)

**Comment by mathbagu** [comment]
Fixed in #176
