### ISSUE TITLE
[IIDM 1.3] Implementation of LoadDetail extension

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-iidm4cpp#157]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
There is no way to know which part of a load's `p0` and `q0` is variable and which part is fixed.

* **What is the expected behavior?**
With this extension, you can specify the variable and fixed parts.

* **Please tell us about your environment:**
  - PowSyBl Version: 3.5.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

cf. powsybl/powsybl-core#1377

**Comment by mathbagu** [comment]
Fix in #177
