### ISSUE TITLE
[IIDM 1.3] Add method to get all tapChanger steps

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-iidm4cpp#158]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the motivation / use case for changing the behavior?**
There is no practical way to iterate on tap changer steps. Adding a method to return all the steps of a tap changer will change that.

* **Please tell us about your environment:**
  - PowSyBl Version: 3.5.0
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

cf powsybl/powsybl-core#1395

**Comment by mathbagu** [comment]
Fixed in #181
