### ISSUE TITLE
[IIDM 1.3] Small fix in DanglingLine's notifications

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-iidm4cpp#159]
* **Do you want to request a *feature* or report a *bug*?**
Bug : this was not the old object that was used in update notifications.

* **Please tell us about your environment:**
  - PowSyBl Version: 3.5.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)
NB: Not sure this bug is present in C++, it was present in Java
cf powsybl/powsybl-core#1400

**Comment by sebalaig** [comment]
Nothing to do in C++ as there is no notification mechanism.
