### ISSUE TITLE
[IIDM v1.3] Terminals getters added to Bus interface

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-iidm4cpp#166]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Connected terminals getters exist but in the BusExt interface (impl package)

* **What is the expected behavior?**
The two getters should be added in the Bus interface.

* **Please tell us about your environment:**
  - PowSyBl Version: 3.5.0
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)
cf powsybl/powsybl-core#1396

**Comment by sebalaig** [comment]
This feature is already present in C++ API.
