### ISSUE TITLE
Support Variants in multi-threading environment

### ISSUE THREAD

**Issue by rosiereflo** [powsybl/powsybl-iidm4cpp#183]
* **Do you want to request a *feature* or report a *bug*?**
feature

* **What is the current behavior?**
Creating and editing variants of a network is not possible in a multi-threading environment.

* **What is the expected behavior?**
We should be able to create a variant of the network for each thread and then let them modify their variant without any conflict with others threads.

See `ThreadLocalMultiVariantContext` in java

**Comment by mathbagu** [comment]
Fix in #277
