### ISSUE TITLE
Option to disable tests

### ISSUE THREAD

**Issue by gautierbureau** [powsybl/powsybl-iidm4cpp#184]
* **Do you want to request a *feature* or report a *bug*?**
Disable test when building

* **What is the current behavior?**
Tests are always built and require boost unit_test_framework to be available for client project that would want to build a release. Maybe it is good the project to run test to see if everything went well ?

* **What is the expected behavior?**
an cmake option like TESTS_ENABLED, should be careful with the CODE_COVERAGE option that would require this option to work

* **What is the motivation / use case for changing the behavior?**
Build a release of the lib without requiring boost unit_test_framework for client project

* **Please tell us about your environment:**
All environments

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by sebalaig** [comment]
Closed by #274
