### ISSUE TITLE
[IIDM v1.0] Make checkAndGetUniqueId static and public

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-iidm4cpp#20]
* **Do you want to request a *feature* or report a *bug*?**
Feature
http://github.com/powsybl/powsybl-core/pull/1021

* **What is the current behavior?**
The feature to automatically fix duplicate ID doesn't exist

* **What is the expected behavior?**
This feature is implemented in both Java and C++

* **What is the motivation / use case for changing the behavior?**
Have both Java and C++ API as close as possible

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by sebalaig** [comment]
This is already OK (done in #81)
