### ISSUE TITLE
compiling with gcc 10.2

### ISSUE THREAD

**Issue by e2l-su** [powsybl/powsybl-iidm4cpp#201]
gcc 10.2 reports an error compiling "math/UndirectedGraph.hxx" line 103. It is a for loop with "unsigned long" which tests that the unsigned long is >=0 (of course always true).
I work on powsybl 1.2.0, using debian bullseye (debian testing)

**Comment by mathbagu** [comment]
We never try to compile the project with g++ 10 or clang-10, so I'm not surprise it doesn't compile. Do you fix this issue on your side and are you able to propose a fix?

**Comment by mathbagu** [comment]
This seems to fix the issue (docker debian:testing with g++ 10)

```
diff --git a/include/powsybl/math/UndirectedGraph.hxx b/include/powsybl/math/UndirectedGraph.hxx
index 7087d76..c15bd72 100644
--- a/include/powsybl/math/UndirectedGraph.hxx
+++ b/include/powsybl/math/UndirectedGraph.hxx
@@ -100,8 +100,8 @@ void UndirectedGraph<V, E>::checkVertex(unsigned long v) const {
 
 template <typename V, typename E>
 void UndirectedGraph<V, E>::cleanVertices(unsigned long v) {
-    for (unsigned long i = v; i >= 0; --i) {
-        const auto& it = m_availableVertices.find(i);
+    for (unsigned long i = 0; i <= v; ++i) {
+        const auto& it = m_availableVertices.find(v - i);
         if (it == m_availableVertices.end()) {
             return;
         }
```

**Comment by mathbagu** [comment]
@e2l-su Do you need a release v1.2.1 or is OK to wait for the next release v1.3.0 ?
