### ISSUE TITLE
Allow overwriting an existing variant 

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-iidm4cpp#209]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
If you clone a variant to an existing one, an exception is thrown. This feature exist in the Java implementation and should also be supported in C++.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
Same implementation that the Java one : https://github.com/powsybl/powsybl-core/pull/790

* **What is the motivation / use case for changing the behavior?**
Have the same implementation in Java and C++

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by sebalaig** [comment]
Closed by #263
