### ISSUE TITLE
Allow to get an extension by its name

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-iidm4cpp#210]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
It's possible to get an extension by it's type, but it's not possible to get it by its name. This feature exists in the java implementation.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
Be able to get an extension by its name.

* **What is the motivation / use case for changing the behavior?**
Have the same implementation in Java and C++

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by sebalaig** [comment]
Closed by #259
