### ISSUE TITLE
Refactor powsybl::iidm::util

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-iidm4cpp#222]
* **Do you want to request a *feature* or report a *bug*?**
Refactoring

* **What is the current behavior?**
In the `powsybl::iidm::util` namespace, we found either classes with static methods, or namespaces. Sometimes they are declared in the `powsybl::iidm` namespace, and sometimes in the `powsybl::iidm::util`.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
I think this is not a good practice to use classes in that case, just to decorate the name of the functions. A utility class could be inherited and we do not want someone to do that. I propose:
- replace the utility classes by namespaces
- remove the extra `util` namespace for these classes

This should be added in the coding style.

* **What is the motivation / use case for changing the behavior?**
Make the API more consistent.

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by sebalaig** [comment]
Closed by PR #270
