### ISSUE TITLE
Connectables parser should call AbstractConnectableXml::read

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-iidm4cpp#226]
* **Do you want to request a *feature* or report a *bug*?**
Potential bug

* **What is the current behavior?**
The connectables parser currently call AbstractIdentifiableXml::read method that is not its direct parent. If we implement AbstractConnectableXml::read we would have to remember to fix the code everywhere.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
We should fix as soon as possible this to avoid a bug in the future. The idea is to replace
`AbstractIdentifiableXml::readSubElements(line, context);`
by
`AbstractConnectableXml<DanglingLine, DanglingLineAdder, VoltageLevel>::readSubElements(line, context);`

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by sebalaig** [comment]
Closed by #269
