### ISSUE TITLE
Enabling C++11 with old cmake version 

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-iidm4cpp#227]
* **Do you want to request a *feature* or report a *bug*?**
Potential bug

* **What is the current behavior?**
With a recent version of cmake, we set the C++11 compatibility mode using the `CMAKE_CXX_STANDARD` option but with an older version, we need to pass the CMAKE_CXX_FLAGS. We saw recently than the gcc option is `-std=c++11` with only one dash whereas we use two in the CMakeLists.

The CMakeFiles.txt require a recent version of cmake, so we have to decide:
- what is the minimum version of cmake to build the project
- remove dead code if the required cmake version is greater than the 3.1.0

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
Remove potential dead code or buggy configuration

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by sebalaig** [comment]
Closed by #264
