### ISSUE TITLE
Rename stdcxx::reference_wrapper

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-iidm4cpp#228]
* **Do you want to request a *feature* or report a *bug*?**
Refactoring

* **What is the current behavior?**
There are two reference_wrapper implementation: the one from the STL that doesn't allow null objects, and the stdcxx implementation that allows null objects. I think it's confusing both classes have the same name and differ only from their namespace.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
I propose the rename the `reference_wrapper` class to `Reference`. The alias already exist so it shouldn't be too long to change that. We probably also have the same conflict with `std::ref` and `std::cref` that could be interesting to rename in the same time, but the number of changes will be higher.

* **What is the motivation / use case for changing the behavior?**
Avoid confusion between powsybl and STL classes

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by sebalaig** [comment]
Closed by PR #266
