### ISSUE TITLE
Make Xml serialiser mandatory when writing extensions

### ISSUE THREAD

**Issue by sebalaig** [powsybl/powsybl-iidm4cpp#239]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
If the extension serializer is not available when writing an extension, the extension is not written in output.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Throw an error if the extension serializer is not available

* **What is the expected behavior?**
Bug fix: ensure that extension XML serializer is not null when writeExtension is called
Bug fix: filter extensions which are not in options during XML export

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

cf. https://github.com/powsybl/powsybl-core/pull/1516

(if a question doesn't apply, you can delete it)

**Comment by mathbagu** [comment]
Fixed
