### ISSUE TITLE
Add FourSubstationsNodeBreakerFactory

### ISSUE THREAD

**Issue by sebalaig** [powsybl/powsybl-iidm4cpp#276]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
FourSubstationsNodeBreakerFactory is not available in C++ repository.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
N/A

* **What is the expected behavior?**
FourSubstationsNodeBreakerFactory is available

* **What is the motivation / use case for changing the behavior?**
Stressfull network.
Improve non-regression.

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

See commit 809f7f16c764887e6d227b2db235579f51d08aee

**Comment by mathbagu** [comment]
Fix in #286
