### ISSUE TITLE
Improve ShuntCompensatorAdder implementation

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-iidm4cpp#292]
* **Do you want to request a *feature* or report a *bug*?**
Feature
https://github.com/powsybl/powsybl-core/pull/1552

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
Ensure that the implementation is equivalent to Java one

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by sebalaig** [comment]
I close this issue because C++ DanglingLineAdder implementation is now consistent with java one (generation instantiated before dangling line and passed to constructor) thanks to PR https://github.com/powsybl/powsybl-iidm4cpp/pull/231.
