### ISSUE TITLE
Put registerExtension in public

### ISSUE THREAD

**Issue by gautierbureau** [powsybl/powsybl-iidm4cpp#302]
* **Do you want to request a *feature* or report a *bug*?**
registerExtension should be public to be able to register extensions in a application where extensions are used and linked directly to the main binary.

* **What is the current behavior?**
Only way to load extensions is with loadExtensions.

* **What is the expected behavior?**
Call registerExtension from client code
`registerExtension(stdcxx::make_unique<ExtensionClass>())`

* **What is the motivation / use case for changing the behavior?**
When using extensions in a main program if the methods of the extensions are used the user is force to link the .so of the extension (or .a) then symbols are already loaded and no need for a dlopen to be called.

**Comment by mathbagu** [comment]
Fixed in #303
