### ISSUE TITLE
typo in Country.hpp

### ISSUE THREAD

**Issue by thiebarrrte** [powsybl/powsybl-iidm4cpp#309]
* **Do you want to request a *feature* or report a *bug*?**
report a bug (typo)

* **What is the current behavior?**
In file include/powsybl/iidm/Country.hpp the copyright notice has some typos :   
Copyright  **=** c) 2017, RTE  **=** http://www.rte-france.com)   
should be :  
Copyright  (c) 2017, RTE  (http://www.rte-france.com)

**Comment by mathbagu** [comment]
Fixed in #310

**Comment by thiebarrrte** [comment]
Sorry if it was not clear, but there were 2 typos, the second one is the   
RTE = http://www.rte-france.com)
part which should be :  
RTE (http://www.rte-france.com)

**Comment by mathbagu** [comment]
Sorry I missunderstood your PR. I just (force) push a fix.
