### ISSUE TITLE
ill-formed format-string exception launched for unregistered extension

### ISSUE THREAD

**Issue by thiebarrrte** [powsybl/powsybl-iidm4cpp#313]
* **Do you want to request a *feature* or report a *bug*?**
report a bug

* **What is the current behavior?**
When an extension is unregistered and if the export option THROW_EXCEPTION_IF_EXTENSION_NOT_FOUND is activated then an exception about ill-formed format-string is launched instead of the expected error message.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
You can modify example3.cpp as below (from line 47) :  

        // Register the serializer for the ActivePowerControl extension
        //auto& extProvider = powsybl::iidm::ExtensionProviders<xml::ExtensionXmlSerializer>::getInstance();
        //extProvider.registerExtension(stdcxx::make_unique<ext::ActivePowerControlXmlSerializer>());

        stdcxx::Properties properties;
        properties.set(powsybl::iidm::converter::ExportOptions::THROW_EXCEPTION_IF_EXTENSION_NOT_FOUND, "true");
        powsybl::iidm::converter::ExportOptions options(properties);
        powsybl::iidm::Network::writeXml(argv[1], network, options);

Notice that registration of extension has been commented and we have THROW_EXCEPTION_IF_EXTENSION_NOT_FOUND export option set.
If you run example3, you get the following error :  
```
terminate called after throwing an instance of 'boost::wrapexcept<boost::io::bad_format_string>'
  what():  boost::bad_format_string: format-string is ill-formed
Aborted (core dumped)
```

* **What is the expected behavior?**
With modified example3 the error should have been :  
`No provider found for extension 'activePowerControl'`

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)
The issue is with src/iidm/ExtensionProviders.cpp file , line 48 :  
`throw PowsyblException(stdcxx::format("No provider found for extension '%1'", name));`  
should be replaced by :  
`throw PowsyblException(stdcxx::format("No provider found for extension '%1%'", name));`

**Comment by mathbagu** [comment]
@thiebarrrte Thank you for the bug report.
