### ISSUE TITLE
Make extension constructor private

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-iidm4cpp#342]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Currently, it's possible to create an extension directly, without using the adder.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
You can then create an extension that is associated to an identifiable, but this extension is not registered in the identifiable. The extension is lost in the XML export

* **What is the expected behavior?**
Forbid the usage of the constructor by making it private.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by sebalaig** [comment]
Fixed by #355 then #371
