### ISSUE TITLE
[IIDM v1.2] Add regulation for shunt compensators

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-iidm4cpp#38]
* **Do you want to request a *feature* or report a *bug*?**
Feature
powsybl/powsybl-core#958
powsybl/powsybl-core#1129
powsybl/powsybl-core#1204

* **What is the current behavior?**
- Regulation is not supported for shunt compensators
- `tapChanger.targetDeadband` is not mandatory when the tap changer is regulating

* **What is the expected behavior?**
- Regulation should be supported for shunt compensators
- `tapChanger.targetDeadband` should be mandatory when the tap changer is regulating (same behaviour for shunt compensators)

* **What is the motivation / use case for changing the behavior?**
Have both Java and C++ API as close as possible

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by sebalaig** [comment]
Fixed in PR #93
