### ISSUE TITLE
[IIDM v1.2] Apparent power attribute on TwoWindingsTransformer and ThreeWindingsTransformer.Leg

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-iidm4cpp#60]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Apparent power is not modeled for `TwoWindingsTransformer` and `ThreeWindingsTransformer.Leg`

* **What is the expected behavior? What is the motivation / use case for changing the behavior?**
It should be modeled to prevent information loss from formats modeling it (e.g. CGMES)

* **Other information**
Linked to PR powsybl/powsybl-core#1199

**Comment by sebalaig** [comment]
Fixed in PR #115
