### ISSUE TITLE
[IIDM v1.2] Add regulation for shunt compensators

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-iidm4cpp#61]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Shunt compensators can not regulate.

* **What is the expected behavior?**
Shunt compensators can regulate in voltage (with a target value, a regulation status, a target deadband and a regulating terminal).

* **What is the motivation / use case for changing the behavior?**
There are formats that model regulation for shunt compensators (e.g. CGMES) and it has an impact on calculations.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

Linked to PR powsybl/powsybl-core#958

**Comment by mathbagu** [comment]
Duplicate #38
