### ISSUE TITLE
[IIDM v1.2] Change behavior of targetDeadband for tap changers

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-iidm4cpp#63]
* **Do you want to request a *feature* or report a *bug*?**
Hard to define

* **What is the current behavior?**
`targetDeadband` is an attribute which is always optional for tap changers.

* **What is the expected behavior?**
`targetDeadband` is a mandatory attribute for tap changers if and only if the regulation is on.

* **What is the motivation / use case for changing the behavior?**
`targetDeadband` is supposed to be mandatory for discrete regulations.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

Linked to PRs powsybl/powsybl-core#958 & powsybl/powsybl-core#1204

**Comment by sebalaig** [comment]
Fixed in PR #93
