### ISSUE TITLE
[IIDM v1.2] Change mechanism for creating and cleaning vertices in a node/breaker voltage level's graph and delete nodeCount attribute in nodeBreakerTopology XML element

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-iidm4cpp#64]
* **Do you want to request a *feature* or report a *bug*?**
Both

* **What is the current behavior?**
The node count can be set in node breaker voltage level. All nodes are pre-created. When an equipment is removed, the vertex is associated to null.

* **What is the expected behavior?**
The node count should be set. It should be updated each time an equipment is attached in the voltage level. All nodes with no equipment attached should not exist or be null.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

Linked to PR powsybl/powsybl-core#1161

**Comment by sebalaig** [comment]
Fixed in PR #137
