### ISSUE TITLE
[IIDM v1.2] Refactor XMLExport to remove the multi file export feature

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-iidm4cpp#65]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
XIIDM can be exported in several files (for base network and extensions)

* **What is the expected behavior? What is the motivation / use case for changing the behavior?**
XIIDM can be exported only in a unique file. However, configuration can be used to export only useful information.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

Linked to PR powsybl/powsybl-core#1215

**Comment by sebalaig** [comment]
Nothing to do because this feature does not already exist in C++.
