### ISSUE TITLE
Add a convenient function to get a Terminal from its node

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-iidm4cpp#67]
* **Do you want to request a *feature* or report a *bug*?**
Feature
https://github.com/powsybl/powsybl-core/pull/1235

* **What is the current behavior?**
The `getTerminal(int node)` method of the NodeBreakerView throw an exception if the node doesn't exist.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
Another method should be added to get an optional of Terminal if the node doesn't exists.

* **What is the motivation / use case for changing the behavior?**
Have both Java and C++ implementation as close as possible.

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by sebalaig** [comment]
Fixed in PR #141
