### ISSUE TITLE
[IIDM 1.2] Introduction to non linear shunt

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-iidm4cpp#69]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Shunts can only be linear

* **What is the expected behavior? What is the motivation / use case for changing the behavior?**
Shunts can be linear or non linear.

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)
Linked to PR powsybl/powsybl-core#1202

**Comment by mathbagu** [comment]
Reverted in v1.2, done in v1.3 (cf. #155)
