### ISSUE TITLE
Implement SimpleAnonymizer

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-iidm4cpp#71]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
The only anonymizer we have is the FakeAnonymizer. We should consider implementing the SimpleAnonymizer.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
Have both Java and C++ implementations as close as possible.

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by sebalaig** [comment]
Closed by #271
