### ISSUE TITLE
[IIDM v1.2] Add convenient methods in VoltageLevel.NodeBreakerView

### ISSUE THREAD

**Issue by MioRtia** [powsybl/powsybl-iidm4cpp#75]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
There is only one method `getTerminal(int node)` in `VoltageLevel.NodeBreakerView` which returns a `Terminal` associated with `node` if it exists, `null` if this node is only associated with a `Switch` or an `InternalConnection` and throws an exception if no equipment is attached to this node.

* **What is the expected behavior?**
We want a `getOptionalTerminal(int node)` method which returns an `Optional<Terminal>` with the linked `Terminal` if it exists or an empty `Optional` if the node is associated with a `Switch`, an `InternalConnection` or has no attached equipment. Furthermore, we want a `hasAttachedEquipment(int node)` which checks if `node` has equipment attached to it.

* **What is the motivation / use case for changing the behavior?**
After the change of building of node/breaker topology, no "empty" vertex is created anymore: if no equipment is attached to a node, the vertex is null, not empty. We want to prevent throwing exceptions in this case.

* **Please tell us about your environment:**
  - PowSyBl Version: 3.3.0-SNAPSHOT

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)
Linked to powsybl/powsybl-core#1235 and powsybl/powsybl-core#1233

**Comment by sebalaig** [comment]
Fixed in PR #141
